[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Scruggs"
authors = [{name = "Jackson Group", email = "jacksonn@illinois.edu"}]
dynamic = ["version", "description"]
